"""Initial migration

Revision ID: edd2f156b2d5
Revises: 
Create Date: 2025-10-15 19:08:52.786397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd2f156b2d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key, auto incrementing'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username, required'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Hashed password, required'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Unique email address, required'),
    sa.Column('nama', sa.String(length=100), nullable=False, comment='Full name, required'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp of user creation, defaults to current time'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
